package com.foreignlang.backend.repository;

import com.foreignlang.backend.entity.EmailHistory;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.UUID;

@Repository
public interface EmailHistoryRepository extends JpaRepository<EmailHistory, UUID> {

    // Find all emails generated by a specific user, most recent first
    List<EmailHistory> findByUserIdOrderByCreatedAtDesc(UUID userId);
}
